version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  default-executor:
    docker:
      - image: circleci/node:8.10.0
jobs:
  test:
    executor: default-executor
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-dependencies-{{ checksum "package-lock.json" }}.
            # fallback to using the latest cache if no exact match is found
            # - v2-dependencies-
      - setup_remote_docker
      - node/install-npm:
        - version: '6.14.2'
      - run: npm ci
      - run:
          name: build run and archive image
          command: |
            PACKAGE_VERSION=$(npm view vue-cli-plugin-e2e-nightwatch-browserstack version)
            TAG=$PACKAGE_VERSION-$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG .
            docker run \
              --name browserstack-plugin-testing \
              -e BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME \
              -e BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY \
              -e BROWSERSTACK_PROJECT=$BROWSERSTACK_PROJECT \
              -e BROWSERSTACK_BUILD=$BROWSERSTACK_BUILD \
              $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG
            docker cp browserstack-plugin-testing:/home/node/app/hello-world/tests/e2e/reports "$(pwd)"/reports
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v2-dependencies-{{ checksum "package-lock.json" }}
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  deploy:
    executor: default-executor
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install-npm:
        - version: '6.14.2'
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters: # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
