version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    steps:
      - checkout
      - run: npm install
      - run: docker build -t vue-nightwatch-browserstack .
      - run: docker run -e BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME -e BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY vue-nightwatch-browserstack
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
