version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG .
          docker run -e BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME -e BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY -e BROWSERSTACK_PROJECT=$BROWSERSTACK_PROJECT $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/vue-cli-plugin-e2e-nightwatch-browserstack:$TAG
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
